identifier_name:
  min_length: 2

line_length:
  warning: 180

disabled_rules:
  - todo
  - trailing_whitespace
  - vertical_parameter_alignment
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - multiline_arguments
  - multiline_parameters

multiline_arguments:
  severity: error

multiline_parameters:
  severity: error
