import Foundation

public extension Strings {
    enum SignUp {}
}
public extension Strings.SignUp {
    static let welcomeScreenTitle = "Hello!"
    static let welcomeScreenInfo = "Community Kitchen helps provide free food to those who need it by enabling the community to share extra or unwanted food."
    static let welcomeButtonTitle = "Register with email"
    static let signUpWithEmailTitle = "Email"
    static let signUpWithEmailPlaceHolder = "Enter your email address"
    static let signUpWithEmailInfo = "First, we'll need to know the email address you want to sign up with.\n \nWe will never share your email with any 3rd parties or send you any emails you don't request."
    static let signUpWithEmailButtonTitle = "Continue to password"
    static let signUpWithPasswordTitle = "Password"
    static let signUpWithPasswordPlaceHolder = "Enter a password"
    static let signUpWithPasswordInfo = "Next, please choose a strong password.\n \nWe recommend using a strong password generated by a password manager."
    static let signUpWithPasswordButtonTitle = "Register"
	static let signUpWithPasswordFailed = "Sorry"
	static let signUpWithPasswordFailedInfo = "Something went wrong. Please enter a valid email or password"
}
